### ISSUE TITLE
結果画面モックアップ作成

### ISSUE THREAD

**Issue by Fukumoto0141** [Fukumoto0141/quiz-app#30]
## 概要 (Summary):
結果画面のモックアップを作成
【XD の画面名】結果画面
【パス名】pages/result-page
## 誰が使うか (For whom):
部屋作成者
部屋参加者
## 何のために or どのように実装するか (For what):
【画面に含める要素】
戻るボタン、ランキングボード
## 達成目標:
結果画面が正しく表示されること

**Comment by k-hayashi-dott** [comment]
結果画面は、倒せたか・倒せなかったの表示に留めましょう。
